In [2]:
# Bismillah

In [1]:
import numpy as np
import pandas as pd

# The Series
    * A one-dimensional array
    * Holds a single data type
    * Allows access to elements through the associated index labels - helps in allignment of multiple series.

In [9]:
np.random.randn(100) # numpy array 

array([ 0.06947148,  0.75256462, -0.91619069,  0.13106665,  0.0441889 ,
        0.09961736,  1.11081896, -1.18823381,  0.38508207, -0.06659066,
       -1.60882551, -1.33385562,  1.00826951,  0.73760252, -0.25293659,
       -0.44215815,  0.97411863, -0.15408026,  1.03287895, -0.98111928,
        0.99435807,  1.27147079,  0.4473407 ,  2.36098393, -0.66034007,
       -0.66883001,  0.37820077, -1.79091076,  0.9799137 ,  0.2533848 ,
       -0.08685739,  0.62057655, -0.95848048,  0.99275171,  0.40296377,
        0.7799859 , -1.00015207,  1.80458237,  1.64165526,  0.99444762,
        0.21693993,  0.57586086,  2.17890247, -0.27454879,  0.50173074,
        0.98998459,  0.24541742,  1.8560003 , -0.77258775,  0.65876788,
       -1.10319603, -1.40521383, -2.50600777, -0.29170676,  0.93143622,
        1.69711105,  1.95613349,  1.95053211, -0.59841903,  2.12999517,
        3.27686283,  0.64701169, -1.05166945, -1.3736395 , -0.75430816,
       -0.24923899, -0.76969545, -0.21464266,  1.44008413,  0.01

In [11]:
s = pd.Series(np.random.randn(100)) # pandas series

In [13]:
s

0    -0.966039
1     0.456244
2     0.695924
3    -0.244621
4     1.676248
        ...   
95   -1.673815
96   -0.655622
97   -0.460615
98    1.771236
99    0.307920
Length: 100, dtype: float64

In [14]:
s[2] # grab a value located at index 2.

0.6959244107504207

In [ ]:
# s[2, 4] # error since no single index, 2 4, exists.

In [15]:
s[[2, 4]] # the inner [] indicates multiple indices given.

2    0.695924
4    1.676248
dtype: float64

In [16]:
s[5:10] # slicing doesn't need [] since there is no confusion.

5    0.410002
6    0.025552
7    0.631885
8   -0.486650
9    1.003634
dtype: float64

In [24]:
s.head()

0   -0.966039
1    0.456244
2    0.695924
3   -0.244621
4    1.676248
dtype: float64

In [18]:
s.tail()

95   -1.673815
96   -0.655622
97   -0.460615
98    1.771236
99    0.307920
dtype: float64

In [19]:
s.shape # 100 rows. Attribute and not method.

(100,)

In [20]:
s.index # Attribute and not method.

RangeIndex(start=0, stop=100, step=1)

In [21]:
s.values

array([-0.96603871,  0.45624442,  0.69592441, -0.24462065,  1.67624791,
        0.41000156,  0.02555209,  0.63188545, -0.48665016,  1.00363424,
       -0.37872146,  0.60697753, -0.88579316, -1.2454294 , -0.5949832 ,
        1.28982789, -0.50002949,  0.21367604, -0.67823495,  1.45533814,
       -3.25995891, -1.00778965, -2.29013493,  0.15855541, -1.37702825,
       -0.31713292,  0.69407917,  0.90681878, -1.50319692,  1.01472288,
        0.31293887,  0.99687391, -0.34650882,  0.42443401, -0.80730991,
        0.36481286, -0.09597013,  0.22658078, -0.30869191, -0.9794911 ,
        1.09647889,  0.97140809,  1.18913682,  0.26722203, -0.73216673,
       -0.80767165, -2.39489612, -0.85835129,  0.20733816, -0.50349377,
        0.01394367,  0.60195117,  1.24377788, -1.36326775, -0.68146211,
        0.7514932 , -0.22338767,  0.85417174, -0.81537448,  0.14458007,
        0.38393731,  0.3070408 , -1.26191382,  0.86953659, -0.97562544,
       -0.78488285, -0.990637  ,  1.41333934, -1.94760166,  0.06

In [25]:
s = pd.Series([1, 2, 3, 4], index = ['a', 'b', 'c', 'd']) 
# [] to indicate multiple values as usual. Indices assigned at the time of constructing a series.
# Series created through a list.

In [26]:
s

a    1
b    2
c    3
d    4
dtype: int64

In [27]:
s = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4})
# Series created through a dictionary. The keys are the indices in the series.

In [28]:
s

a    1
b    2
c    3
d    4
dtype: int64

In [29]:
s = pd.Series([1, 2, 3, 4, np.nan])
# np.nan so that the pandas know that this value is missing.

In [30]:
s

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
dtype: float64

In [31]:
len(s)
# includes a missing avalue as well.

5

In [32]:
s.count()
# excludes missing value.

4

In [33]:
s = pd.Series([10, 3 , 4, 5, 7, 7, 9, 10, np.nan])

In [34]:
s

0    10.0
1     3.0
2     4.0
3     5.0
4     7.0
5     7.0
6     9.0
7    10.0
8     NaN
dtype: float64

In [37]:
s.unique()
# returns only unique values. That is, avoid repeatition of the same value.
# returns the missing value as well.

array([10.,  3.,  4.,  5.,  7.,  9., nan])

In [36]:
s.value_counts()
# returns frrequency distribution in descending order. For ascending order, ascending = True.
# excludes a missing value.

10.0    2
7.0     2
3.0     1
4.0     1
5.0     1
9.0     1
dtype: int64

In [38]:
s.value_counts(ascending = True) # go from smaller values to larger values.

3.0     1
4.0     1
5.0     1
9.0     1
10.0    2
7.0     2
dtype: int64

In [39]:
s.value_counts(normalize = True) # to grab percentages. ascending = False is the default argument.


10.0    0.250
7.0     0.250
3.0     0.125
4.0     0.125
5.0     0.125
9.0     0.125
dtype: float64

In [40]:
s1 = pd.Series([1, 2, 3, 4], index = ['a', 'b', 'c', 'd'])
s2 = pd.Series([4, 3, 2, 1], index = ['d', 'c', 'b', 'a'])

In [41]:
s1 + s2
# The allignment is done automatically on the basis of index labels.
# This feature does not exist in numpy array. See below.

a    2
b    4
c    6
d    8
dtype: int64

In [43]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([4, 3, 2, 1])

In [44]:
a1

array([1, 2, 3, 4])

In [45]:
a2

array([4, 3, 2, 1])

In [46]:
a1 + a2
# each corresponding element from both the arrays must be added. No flexibility of adding any two desriable elements of
# array located at different indices.

array([5, 5, 5, 5])